// Explicit parameter types for 4D 20's legacy no-inference compiler mode.
C_TEXT(AXB_Poll; $1)
C_OBJECT(AXB_Pulse; $1)
C_OBJECT(AXB_Start; $0; $1)
C_OBJECT(AXB_CoreWindows)
C_TEXT(AXB_Dispatch; $1)
C_OBJECT(AXB_Dispatch; $0; $2)
C_OBJECT(AXB_ALPNode; $0)
C_TEXT(AXB_ALPNode; $1; $2; $3)
C_OBJECT(AXB_ALPSelect; $0; $4)
C_LONGINT(AXB_ALPSelect; $1)
C_POINTER(AXB_ALPSelect; $2)
C_TEXT(AXB_ALPSelect; $3)
C_COLLECTION(AXB_ALPTable; $0)
C_LONGINT(AXB_ALPTable; $1)
C_TEXT(AXB_ALPTable; $2; $4)
C_POINTER(AXB_ALPTable; $3)
C_OBJECT(AXB_ControlNode; $0)
C_TEXT(AXB_ControlNode; $1; $2; $3; $4)
C_VARIANT(AXB_ControlNode; $5)
C_BOOLEAN(AXB_ControlNode; $6)
C_COLLECTION(AXB_ALPRows; $0)
C_LONGINT(AXB_ALPRows; $1)
C_TEXT(AXB_ALPRows; $2)
C_POINTER(AXB_ALPRows; $3)
C_OBJECT(AXB_ALPRows; $4)
C_OBJECT(AXB_ALPRowsSelect; $0; $4; $5)
C_LONGINT(AXB_ALPRowsSelect; $1)
C_TEXT(AXB_ALPRowsSelect; $2)
C_POINTER(AXB_ALPRowsSelect; $3)
C_TEXT(AXB_ALPGrid; $1)
C_OBJECT(AXB_ALPGrid; $0; $2; $3; $4)
C_TEXT(AXB_ALPGridAction; $1)
C_OBJECT(AXB_ALPGridAction; $0; $2; $3; $4)
C_OBJECT(AXB_ALPGridConfirm; $0; $1)

C_OBJECT(AXB_ALPEditor; $0; $1)
C_TEXT(AXB_ALPEditor; $2)
C_COLLECTION(AXB_ALPEditor; $3)
