#!/usr/bin/env python3
"""Install portable bridge host methods into a 4D source project, without binaries."""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
MARKER = "// Generated by AccessibilityBridge/install_host_methods.py; body SHA256: "
BEGIN = "// Accessibility bridge host declarations begin"
END = "// Accessibility bridge host declarations end"
AREA_METHODS = {"AXB_ALPNode", "AXB_ALPRows", "AXB_ALPRowsSelect", "AXB_ALPSelect",
                "AXB_ALPGrid", "AXB_ALPGridAction", "AXB_ALPGridConfirm", "AXB_ALPGridValue", "AXB_ALPEditor"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-dir", required=True, type=Path, help="Directory containing Sources/Methods")
    parser.add_argument("--compiler-method", default="Compiler_AXBHost", help="Compiler method to create or update")
    parser.add_argument("--area-list", action="store_true", help="Also install the AreaList grid and legacy row adapters")
    args = parser.parse_args()
    methods = args.project_dir / "Sources/Methods"
    if not methods.is_dir():
        parser.error("--project-dir must already contain Sources/Methods")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", args.compiler_method):
        parser.error("--compiler-method must be a method name")
    sources = [p for p in sorted((ROOT / "host/OptionalMethods").glob("*.4dm")) if not p.stem.startswith("Compiler_")]
    if args.area_list:
        sources += [ROOT / "host/Methods" / (name + ".4dm") for name in sorted(AREA_METHODS)]
    expected_names = {p.name for p in sources}
    orphans = []
    for target in methods.glob("AXB_*.4dm"):
        if target.name not in expected_names and target.read_text().startswith(MARKER):
            orphans.append(target.name)
    if orphans:
        parser.error("Previously generated methods would be orphaned: " + ", ".join(sorted(orphans)) + ". Keep their install options or remove the methods and declarations deliberately.")
    changes = {}
    for path in sources:
        body = path.read_text()
        target = methods / path.name
        if target.exists():
            old = target.read_text()
            header, _, old_body = old.partition("\n")
            if not header.startswith(MARKER) or header[len(MARKER):] != hashlib.sha256(old_body.encode()).hexdigest():
                parser.error(f"Refusing to replace a non-generated or edited method: {target}")
        changes[target] = MARKER + hashlib.sha256(body.encode()).hexdigest() + "\n" + body
    declarations = (ROOT / "host/OptionalMethods/Compiler_AXBHost.4dm").read_text().splitlines()
    if args.area_list:
        for line in (ROOT / "host/Methods/Compiler_AXB.4dm").read_text().splitlines():
            match = re.search(r"\((AXB_\w+);", line)
            if match and match[1] in AREA_METHODS:
                declarations.append(line)
    compiler = methods / (args.compiler_method + ".4dm")
    for other in methods.glob("*.4dm"):
        if other == compiler:
            continue
        content = other.read_text()
        if BEGIN in content or END in content:
            parser.error(f"Bridge declarations already exist in {other.stem}. Keep that compiler target or move its marked block deliberately before reinstalling.")
    old = compiler.read_text() if compiler.exists() else ""
    block = BEGIN + "\n" + "\n".join(declarations) + "\n" + END
    if BEGIN in old or END in old:
        if old.count(BEGIN) != 1 or old.count(END) != 1 or old.index(BEGIN) > old.index(END):
            parser.error("Compiler method has ambiguous bridge declaration markers")
        prefix, tail = old.split(BEGIN)
        _, suffix = tail.split(END)
        changes[compiler] = prefix + block + suffix
    else:
        changes[compiler] = old.rstrip() + "\n\n" + block + "\n"
    for target, text in changes.items():
        target.write_text(text)
    print(f"Installed {len(sources)} host methods and declarations in {compiler}; no packages or data changed.")


if __name__ == "__main__":
    main()
