#!/usr/bin/env python3
"""Install portable bridge host methods into a 4D source project, without binaries."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
MARKER = "// Generated by AccessibilityBridge/install_host_methods.py; body SHA256: "
BEGIN = "// Accessibility bridge host declarations begin"
END = "// Accessibility bridge host declarations end"
AREA_METHODS = {"AXB_ALPNode", "AXB_ALPRows", "AXB_ALPRowsSelect", "AXB_ALPSelect",
                "AXB_ALPGrid", "AXB_ALPGridAction", "AXB_ALPGridConfirm", "AXB_ALPGridValue", "AXB_ALPEditor"}
AREA_NAME = "__AXB_Bridge"
AREA_KIND = "%AXB Area"
AREA = {"type": "plugin", "pluginAreaKind": AREA_KIND, "dataSource": "",
        "left": 0, "top": 0, "width": 1, "height": 1, "enterable": False,
        "focusable": False, "printable": False}


def area_form(form, configuration=""):
    """Return a copy with one lifecycle area; never change existing objects."""
    if not isinstance(form, dict):
        raise ValueError("Form must be an object")
    if configuration and not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]{0,63}", configuration):
        raise ValueError("Invalid area configuration key")
    if form.get("destination") not in (None, "", "detailScreen"):
        raise ValueError("Lifecycle areas require a detail screen or unspecified destination")
    result = json.loads(json.dumps(form))
    area_name = AREA_NAME + ("." + configuration if configuration else "")
    pages = result.get("pages")
    if not isinstance(pages, list) or not pages:
        raise ValueError("Form must have a pages collection")
    found = []
    for number, page in enumerate(pages):
        if page is None:
            continue
        if not isinstance(page, dict) or not isinstance(page.get("objects", {}), dict):
            raise ValueError("Invalid form page or objects")
        for name, obj in page.get("objects", {}).items():
            if not isinstance(obj, dict):
                raise ValueError("Invalid form object: " + name)
            if name == AREA_NAME or name.startswith(AREA_NAME + ".") or obj.get("pluginAreaKind") == AREA_KIND:
                found.append((number, name, obj))
    if found:
        if found != [(0, area_name, AREA)]:
            raise ValueError("Existing lifecycle area differs from the installer-owned area")
        return result
    if pages[0] is None:
        pages[0] = {"objects": {}}
    pages[0].setdefault("objects", {})[area_name] = AREA.copy()
    return result


def form_changes(project, names, all_forms):
    """Preflight every selected form before any helper or form is written."""
    if not names and not all_forms:
        # A method-only refresh never reads or parses application forms.
        return {}
    paths = sorted((project / "Sources/Forms").glob("*/form.4DForm"))
    paths += sorted((project / "Sources/TableForms").glob("*/*/form.4DForm"))
    by_name = {str(p.parent.relative_to(project / "Sources")): p for p in paths}
    selected = paths if all_forms else []
    for name in names:
        key = name if name.startswith(("Forms/", "TableForms/")) else "Forms/" + name
        if key not in by_name:
            raise ValueError("Unknown form: " + name)
        selected.append(by_name[key])
    originals = {p: p.read_text() for p in paths}
    forms = {p: json.loads(text) for p, text in originals.items()}
    table_names = {}
    catalog = project / "Sources/catalog.4DCatalog"
    if catalog.is_file():
        for table in ET.parse(catalog).iter("table"):
            if table.get("name") and table.get("id"):
                table_names[table.get("name")] = table.get("id")

    def parent(path):
        form = forms[path]
        inherited = form.get("inheritedForm")
        if inherited in (None, "", " "):
            return None
        if not isinstance(inherited, str) or "/" in inherited or "\\" in inherited:
            raise ValueError("Resolve external/inline inherited forms before adding an area: " + str(path.relative_to(project)))
        table = form.get("inheritedFormTable")
        if table in (None, "", " ", 0):
            key = "Forms/" + inherited
        else:
            number = table_names.get(str(table), str(table))
            key = "TableForms/" + number + "/" + inherited
        if key not in by_name:
            raise ValueError("Unknown inherited form " + key + " in " + str(path.relative_to(project)))
        return by_name[key]

    def base(path, chain):
        if path in chain:
            raise ValueError("Inherited form cycle: " + str(path.relative_to(project)))
        # Validate any local area before considering inherited ownership.
        checked = area_form(forms[path])
        inherited = parent(path)
        if inherited is None:
            return path
        owner = base(inherited, [*chain, path])
        if checked == forms[path]:
            raise ValueError("Remove the installer-owned area from the derived form; its base owns lifecycle: " + str(path.relative_to(project)))
        return owner

    owners = set()
    for path in sorted(set(selected)):
        if all_forms and forms[path].get("destination") not in (None, "", "detailScreen"):
            print("Skipped non-detail form: " + str(path.relative_to(project)))
            continue
        owners.add(base(path, []))
    # A selected derived form changes its shared base. Report every known
    # descendant, including unselected list/print forms, before any writes.
    parents = {}
    for path in paths:
        try:
            parents[path] = parent(path)
        except ValueError:
            continue  # Unrelated unresolved inheritance is not modified.
    for owner in sorted(owners):
        affected = []
        for path in paths:
            current, visited = path, set()
            while current in parents and current not in visited:
                visited.add(current)
                current = parents[current]
                if current == owner:
                    affected.append(str(path.relative_to(project)) + " [" + forms[path].get("destination", "unspecified") + "]")
                    break
        if affected:
            print("Shared lifecycle base: " + str(owner.relative_to(project)))
            for name in affected:
                print("  Inherited by: " + name)
    changes = {}
    for path in sorted(owners):
        original = originals[path]
        form = forms[path]
        updated = area_form(form)
        if updated != form:
            # Preserve the existing project's tab/space convention. All layout,
            # events, methods and existing object values remain identical.
            indent = "\t" if re.search(r"\n\t+\S", original) else 2
            changes[path] = json.dumps(updated, ensure_ascii=False, indent=indent) + "\n"
    return changes


def main(argv=None, *, transform=None):
    """Install sources, optionally applying a trusted application's instrumentation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-dir", required=True, type=Path, help="Directory containing Sources/Methods")
    parser.add_argument("--compiler-method", default="Compiler_AXBHost", help="Compiler method to create or update")
    parser.add_argument("--area-list", action="store_true", help="Also install the AreaList grid and legacy row adapters")
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--form", action="append", default=[], help="Add an area to a named form (repeatable); use TableForms/<table>/<form> for table forms")
    selection.add_argument("--all-forms", action="store_true", help="Add areas to detail forms, once per inheritance chain; skip list/print forms")
    parser.add_argument("--dry-run", action="store_true", help="Validate and list changes without writing")
    args = parser.parse_args(argv)
    methods = args.project_dir / "Sources/Methods"
    if not methods.is_dir():
        parser.error("--project-dir must already contain Sources/Methods")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", args.compiler_method):
        parser.error("--compiler-method must be a method name")
    sources = [p for p in sorted((ROOT / "host/OptionalMethods").glob("*.4dm")) if not p.stem.startswith("Compiler_")]
    if args.area_list:
        sources += [ROOT / "host/Methods" / (name + ".4dm") for name in sorted(AREA_METHODS)]
    expected_names = {p.name for p in sources}
    orphans = []
    for target in methods.glob("AXB_*.4dm"):
        if target.name not in expected_names and target.read_text().startswith(MARKER):
            orphans.append(target.name)
    if orphans:
        parser.error("Previously generated methods would be orphaned: " + ", ".join(sorted(orphans)) + ". Keep their install options or remove the methods and declarations deliberately.")
    changes = {}
    for path in sources:
        body = path.read_text()
        if transform is not None:
            body = transform(body, path.stem)
        target = methods / path.name
        if target.exists():
            old = target.read_text()
            header, _, old_body = old.partition("\n")
            if not header.startswith(MARKER) or header[len(MARKER):] != hashlib.sha256(old_body.encode()).hexdigest():
                parser.error(f"Refusing to replace a non-generated or edited method: {target}")
        changes[target] = MARKER + hashlib.sha256(body.encode()).hexdigest() + "\n" + body
    declarations = (ROOT / "host/OptionalMethods/Compiler_AXBHost.4dm").read_text().splitlines()
    if args.area_list:
        for line in (ROOT / "host/Methods/Compiler_AXB.4dm").read_text().splitlines():
            match = re.search(r"\((AXB_\w+);", line)
            if match and match[1] in AREA_METHODS:
                declarations.append(line)
    compiler = methods / (args.compiler_method + ".4dm")
    for other in methods.glob("*.4dm"):
        if other == compiler:
            continue
        content = other.read_text()
        if BEGIN in content or END in content:
            parser.error(f"Bridge declarations already exist in {other.stem}. Keep that compiler target or move its marked block deliberately before reinstalling.")
    old = compiler.read_text() if compiler.exists() else ""
    block = BEGIN + "\n" + "\n".join(declarations) + "\n" + END
    if BEGIN in old or END in old:
        if old.count(BEGIN) != 1 or old.count(END) != 1 or old.index(BEGIN) > old.index(END):
            parser.error("Compiler method has ambiguous bridge declaration markers")
        prefix, tail = old.split(BEGIN)
        _, suffix = tail.split(END)
        changes[compiler] = prefix + block + suffix
    else:
        changes[compiler] = old.rstrip() + "\n\n" + block + "\n"
    try:
        forms = form_changes(args.project_dir, args.form, args.all_forms)
    except (ValueError, OSError, ET.ParseError) as failure:
        parser.error(str(failure))
    changes.update(forms)
    if args.dry_run:
        for target, content in changes.items():
            if not target.exists() or target.read_text() != content:
                print(target.relative_to(args.project_dir))
        return
    for target, content in changes.items():
        if not target.exists() or target.read_text() != content:
            target.write_text(content)
    print(f"Installed {len(sources)} host methods and declarations in {compiler}; added {len(forms)} lifecycle areas; no packages or data changed.")


if __name__ == "__main__":
    main()
