 // Existing application checkbox configuration, with no accessibility hooks.
 $error:=AL_SetArraysNam(Form.area; 8; 1; $prefix+"Direct")
 $error:=AL_SetArraysNam(Form.area; 9; 1; $prefix+"Focusable")
 $error:=AL_SetArraysNam(Form.area; 10; 1; $prefix+"Mixed")
 $error:=AL_SetArraysNam(Form.area; 11; 1; $prefix+"Numeric")
 AL_SetAreaLongProperty(Form.area; ALP_Area_Compatibility; 0)
 var $column : Integer
 For ($column; 8; 11)
  AL_SetColumnRealProperty(Form.area; $column; ALP_Column_Width; 120; 1)
  AL_SetColumnLongProperty(Form.area; $column; ALP_Column_Enterable; 1)
  AL_SetColumnLongProperty(Form.area; $column; ALP_Column_DisplayControl; 0)
  AL_SetColumnLongProperty(Form.area; $column; ALP_Column_Visible; 1)
 End for
 AL_SetColumnLongProperty(Form.area; 7; ALP_Column_Visible; 0)
 AL_SetColumnTextProperty(Form.area; 8; ALP_Column_HeaderText; "Direct"; 1)
 AL_SetColumnTextProperty(Form.area; 9; ALP_Column_HeaderText; "Focusable"; 1)
 AL_SetColumnTextProperty(Form.area; 10; ALP_Column_HeaderText; "Mixed"; 1)
 AL_SetColumnTextProperty(Form.area; 11; ALP_Column_HeaderText; "Numeric"; 1)
 AL_SetColumnLongProperty(Form.area; 8; ALP_Column_HorAlign; 1)
 AL_SetColumnLongProperty(Form.area; 9; ALP_Column_HorAlign; 2)
 AL_SetColumnLongProperty(Form.area; 10; ALP_Column_HorAlign; 3)
 AL_SetColumnLongProperty(Form.area; 9; ALP_Column_FocusableCheckbox; 1)
 AL_SetColumnLongProperty(Form.area; 9; ALP_Column_DisplayControl; 1)
 AL_SetColumnLongProperty(Form.area; 11; ALP_Column_DisplayControl; 2)
 AL_SetColumnLongProperty(Form.area; 10; ALP_Column_EntryControl; 1)
 AL_SetCellLongProperty(Form.area; 4; 8; ALP_Cell_Enterable; 0; 1; 1)
 AL_SetCellLongProperty(Form.area; 5; 8; ALP_Cell_Invisible; 1; 1; 1)
 AL_SetCellTextProperty(Form.area; 7; 8; ALP_Cell_Format; Char(8226); 1; 1)
