C_TEXT(AXB_Host; $1)
C_OBJECT(AXB_Host; $0; $2)
C_TEXT(AXB_Form; $1)
C_OBJECT(AXB_Form; $0; $2)
C_OBJECT(AXB_View; $0; $1)
C_OBJECT(AXB_Discover; $0; $1)
C_OBJECT(AXB_ControlKey; $0; $1)
C_TEXT(AXB_ControlValue; $0)
C_VARIANT(AXB_ControlValue; $1)
C_TEXT(AXB_ControlValue; $2)
C_OBJECT(AXB_ControlAction; $0; $1; $2)
C_OBJECT(AXB_ControlConfirm; $0; $1)
C_OBJECT(AXB_TextAction; $0; $1; $2; $3)
C_OBJECT(AXB_TextStep; $0; $1)
C_OBJECT(AXB_TextReady; $0; $1)
C_COLLECTION(AXB_Controls; $1)
C_OBJECT(AXB_Controls; $0)
C_COLLECTION(AXB_Intersects; $1; $2)
C_BOOLEAN(AXB_Intersects; $0)
C_OBJECT(AXB_PollGuard)
C_OBJECT(AXB_FormFailed; $1; $2)
C_OBJECT(AXB_Result; $0; $1)
C_OBJECT(AXB_Listbox; $0; $1)
C_OBJECT(AXB_ListboxSelect; $0; $1; $2)
C_OBJECT(AXB_ListboxConfirm; $0; $1)
C_OBJECT(AXB_Dynamic; $0; $1; $2; $3)
C_TEXT(AXB_Dynamic; $4)
C_OBJECT(AXB_DynamicStop; $1; $2)
C_OBJECT(AXB_DynamicFailure; $1; $2)
C_TEXT(AXB_DynamicFailure; $3)
C_OBJECT(AXB_ViewCreate; $0; $1)
C_OBJECT(AXB_FormRoots)
C_TEXT(AXB_Invalidate; $1)
C_OBJECT(AXB_Invalidate; $0)
C_OBJECT(AXB_FormTree; $0)
C_OBJECT(AXB_FormContext; $0)
C_OBJECT(AXB_FormEvent; $0)
C_TEXT(AXB_FormEvent; $1)
C_OBJECT(AXB_FormStop; $1)
C_OBJECT(AXB_Focus; $0)
C_TEXT(AXB_ControlFocus; $1)
C_BOOLEAN(AXB_ControlFocus; $0)
C_OBJECT(AXB_Grids; $0; $1; $2)
C_TEXT(AXB_GridListbox; $1)
C_OBJECT(AXB_GridListbox; $0; $2; $3; $4)
C_TEXT(AXB_GridListboxAction; $1)
C_OBJECT(AXB_GridListboxAction; $0; $2; $3; $4)
C_OBJECT(AXB_GridGeometry; $0; $1)
C_COLLECTION(AXB_GridGeometry; $2; $3)
C_OBJECT(AXB_GridPoll; $1; $2)
C_COLLECTION(AXB_GridPoll; $3)
C_OBJECT(AXB_GridListboxConfirm; $0; $1)
C_TEXT(AXB_TextFocus; $1)
C_OBJECT(AXB_TextFocus; $2)
C_BOOLEAN(AXB_TextFocus; $0)
C_OBJECT(AXB_TextSelect; $0; $1)
C_OBJECT(AXB_GridOptions; $1)
C_BOOLEAN(AXB_GridOptions; $0)
C_COLLECTION(AXB_KeyIndex; $1)
C_TEXT(AXB_KeyIndex; $2)
C_LONGINT(AXB_KeyIndex; $0)

C_OBJECT(AXB_TextEditor; $0; $1)
C_TEXT(AXB_TextEditor; $2)
C_COLLECTION(AXB_TextEditor; $3)

C_LONGINT(AXB_TextIndex; $0; $2)
C_TEXT(AXB_TextIndex; $1)
C_BOOLEAN(AXB_TextIndex; $3)

C_PICTURE(AXB_PictureEquals; $1; $2)
C_BOOLEAN(AXB_PictureEquals; $0)
C_COLLECTION(AXB_ControlGroups; $1)
C_OBJECT(AXB_ControlGroups; $2)
C_COLLECTION(AXB_ControlGroups; $0)
C_TEXT(AXB_PopupValue; $1)
C_POINTER(AXB_PopupValue; $2)
C_OBJECT(AXB_PopupValue; $0)
C_OBJECT(AXB_GridBinding; $0; $1)
C_OBJECT(AXB_GridValue; $0; $1; $2)
C_LONGINT(AXB_GridValue; $3)
C_TEXT(AXB_ScrollChild; $1)
C_COLLECTION(AXB_ScrollChild; $2)
C_OBJECT(AXB_ScrollChild; $0)

C_COLLECTION(AXB_ControlPoint; $0; $2; $4)
C_OBJECT(AXB_ControlPoint; $1; $3)
